<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Cache\Cache;


/**
 * @file
 * Primary module hooks for Architsaudi module.
 */

/**
 * Implements hook_page_attachments().
 */
function majlis_page_attachments(array &$attachments) {
  // Attach the global library to all pages including admin
  $attachments['#attached']['library'][] = 'majlis/global';
}

/**
 * Implements hook_theme().
 */
function majlis_theme($existing, $type, $theme, $path)
{
    return [
    'about_block' => [
      'variables' => ['items' => []],
      'template' => 'about-block',
    ],
    'form_block' => [
      'variables' => ['items' => []],
      'template' => 'form-block',
    ],
    'header_block' => [
      'variables' => ['items' => []],
      'template' => 'header-block',
    ],
  ];
}